FROM rastasheep/ubuntu-sshd:16.04
MAINTAINER armagast@gmail.com
# Installation of wordpress

RUN apt-get update && apt-get install -y supervisor nginx
RUN mkdir -p/var/run/sshd /var/log/supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

#ADD configure_nginx.sh /home/

#RUN ["chmod","+x","/home/configure_nginx.sh"] 
#RUN /home/configure_nginx.sh && rm /home/configure_nginx.sh 

EXPOSE 22 80

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
